spring:
  application:
    name: ai-assistant
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          model: gemini-2.0-flash
          options:
            temperature: 0
            top-p: 1
            num-ctx: 2048
        embedding:
          api-key: ${GOOGLE_API_KEY}
          model: text-embedding-001
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: 6334
        api-key: ${QDRANT_API_KEY}
        initialize-schema: true
        collection-name: policy_data
        use-tls: true
server:
  port: 8080
