server:
  port: 8080

spring:
  application:
    name: ai-assistant

  ai:
    model:
      chat: google-genai
      embedding:
        text: google-genai

    google:
      genai:
        api-key: ${GOOGLE_API_KEY}

        chat:
          options:
            model: gemma-4-31b-it
            temperature: 0.0
            top-p: 1.0
            max-output-tokens: 2048
            stream: true

        embedding:
          api-key: ${GOOGLE_API_KEY}
          text:
            options:
              model: text-embedding-004
              task-type: RETRIEVAL_DOCUMENT

    vectorstore:
      qdrant:
        host: ${QDRANT_HOST}
        port: 6334
        api-key: ${QDRANT_API_KEY}
        initialize-schema: true
        collection-name: policy_data
        use-tls: true